# Generated by Django 5.0.4 on 2024-04-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='due_date',
        ),
    ]
